### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by binuraj-rs** [leleuj/cas-pac4j-oauth-demo#21]
Hi,

I tried with "Authenticate with another CAS server using OAuth v2.0 protocol". I tried "leleuj" as credential. The login was successful. But my doubt is after login the oauth2 redirection does not work. I can see in the address bar "redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fcas%2Flogin" like this. But it is not working.

The full url after successfull login is:-

http://localhost:8080/cas2/login;jsessionid=3r00jorz4r0i1cu37yn7yrqix?response_type=code&client_id=this_is_the_key&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fcas%2Flogin%3Fclient_name%3DCasOAuthWrapperClient

**Comment by leleuj** [comment]
Indeed, it does not work with the Jetty plugin, but it works perfectly with a regular Tomcat installation. I don't know what's wrong again with this Jetty plugin, but it seems the redirection does not happen. You should be redirected to: http://localhost:8080/cas2/login?service=http%3A%2F%2Flocalhost%3A8080%2Fcas2%2Foauth2.0%2FcallbackAuthorize

I will rework the OAuth server support, maybe it'll fix that issue.

**Comment by leleuj** [comment]
It's now fixed.
