### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by EMRJ** [leleuj/cas-pac4j-oauth-demo#24]
Got the following build error when I run mvn clean package

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

Missing:
----------
1) org.pac4j:pac4j-http:jar:1.8.1-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.pac4j -DartifactId=pac4j-http -Dversion=1.8.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.pac4j -DartifactId=pac4j-http -Dversion=1.8.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.leleuj:cas-pac4j-oauth-client-demo:war:4.2.0-SNAPSHOT
  	2) org.pac4j:pac4j-http:jar:1.8.1-SNAPSHOT

2) org.pac4j:pac4j-cas:jar:1.8.1-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.pac4j -DartifactId=pac4j-cas -Dversion=1.8.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.pac4j -DartifactId=pac4j-cas -Dversion=1.8.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.leleuj:cas-pac4j-oauth-client-demo:war:4.2.0-SNAPSHOT
  	2) org.pac4j:pac4j-cas:jar:1.8.1-SNAPSHOT

3) org.pac4j:pac4j-saml:jar:1.8.1-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.pac4j -DartifactId=pac4j-saml -Dversion=1.8.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.pac4j -DartifactId=pac4j-saml -Dversion=1.8.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.leleuj:cas-pac4j-oauth-client-demo:war:4.2.0-SNAPSHOT
  	2) org.pac4j:pac4j-saml:jar:1.8.1-SNAPSHOT

4) org.pac4j:pac4j-oauth:jar:1.8.1-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.pac4j -DartifactId=pac4j-oauth -Dversion=1.8.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.pac4j -DartifactId=pac4j-oauth -Dversion=1.8.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.leleuj:cas-pac4j-oauth-client-demo:war:4.2.0-SNAPSHOT
  	2) org.pac4j:pac4j-oauth:jar:1.8.1-SNAPSHOT

5) org.pac4j:pac4j-openid:jar:1.8.1-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.pac4j -DartifactId=pac4j-openid -Dversion=1.8.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.pac4j -DartifactId=pac4j-openid -Dversion=1.8.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.leleuj:cas-pac4j-oauth-client-demo:war:4.2.0-SNAPSHOT
  	2) org.pac4j:pac4j-openid:jar:1.8.1-SNAPSHOT

----------
5 required artifacts are missing.

for artifact: 
  org.leleuj:cas-pac4j-oauth-client-demo:war:4.2.0-SNAPSHOT

from the specified remote repositories:
  jasig-developer-repo (http://developer.jasig.org/repo/content/groups/m2-legacy/),
  central (http://repo1.maven.org/maven2),
  sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots),
  shibboleth-public-repo (https://build.shibboleth.net/nexus/content/groups/public),
  mule-public (https://repository.mulesoft.org/nexus/content/repositories/public)

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 minutes 50 seconds
[INFO] Finished at: Mon Dec 28 12:30:07 IST 2015
[INFO] Final Memory: 37M/297M
[INFO] ------------------------------------------------------------------------

**Comment by leleuj** [comment]
Yes, pac4j has been released so you should use pac4j v1.8.1. It just fixed it, it should be ok now.
