### ISSUE TITLE
On validateService i get ticket not recognised error

### ISSUE THREAD

**Issue by vysak** [leleuj/cas-pac4j-oauth-demo#26]
Any Idea why I am getting ticket not recognised error on validateService request from my client. I am using the OAuthClient Demo as is without changing anything, but added google oauth2 in the pac4j context xml. Any reason why do I get this error. 

As per documentation it says its because service name validation issue, but i cross verified the service name that i using for code generation and validateService request both are same

**Comment by leleuj** [comment]
Strange: "ticket not recognized" happens when using the CAS protocol, not sure how this can be related to the Google OAuth 2 provider.

Can you elaborate a little more?

**Comment by vysak** [comment]
I could able to fix it, the problem was due to wrong choice of library versions...Thanks for looking into this.
