### ISSUE TITLE
Maven 2 fails to handle HTTP 301 result codes properly

### ISSUE THREAD

**Issue by riaanvddool** [leleuj/cas-pac4j-oauth-demo#30]
https://issues.apache.org/jira/browse/MNG-4838

Please add a section in the README to alert users to this fact. My Ubuntu 14.04 Gnome machine with OpenJDK had maven2 installed and failed to build properly because of the 301s.

**Comment by riaanvddool** [comment]
To install maven 3:

    #sudo apt-get remove maven2
    sudo add-apt-repository "deb http://ppa.launchpad.net/natecarlson/maven3/ubuntu precise main"
    sudo apt-get update
    sudo apt-get install maven3

    #If you encounter this:
    #The program 'mvn' can be found in the following packages:
    # * maven
    # * maven2
    #Try sudo apt-get install <selected-page>

    #Just add those lines in /etc/profile
    export M2_HOME=/usr/share/maven3
    export M2=$M2_HOME/bin
    export PATH=$M2:$PATH

https://gist.github.com/stephou0104/8fa47ddfe1afede6e310

**Comment by leleuj** [comment]
OK. Would you mind submitting a PR to update the README? Thanks
