### ISSUE TITLE
mvn clean package  -- gives error

### ISSUE THREAD

**Issue by jjayaraman** [leleuj/cas-pac4j-oauth-demo#31]
Many thanks for the nice projects.

I tried to issue the below commands as per the Readme doc

cd cas-pac4j-oauth-demo
mvn clean package

And got a build failure with below error message

[INFO] Copying webapp resources [C:\Git_projects\cas-pac4j-oauth-demo\cas-pac4j-oauth-server-demo\src\main\webapp]
[INFO] Processing overlay [ id org.jasig.cas:cas-server-webapp]
[INFO] Webapp assembled in [17010 msecs]
[INFO] Building war: C:\Git_projects\cas-pac4j-oauth-demo\cas-pac4j-oauth-server-demo\target\cas-pac4j-oauth-server-demo.war
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] CAS Pac4J / OAuth demo ............................. SUCCESS [  0.152 s]
[INFO] CAS Pac4J / OAuth client demo ...................... SUCCESS [ 22.663 s]
[INFO] CAS Pac4J / OAuth server demo ...................... FAILURE [ 20.487 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.454 s
[INFO] Finished at: 2016-05-26T10:52:42+01:00
[INFO] Final Memory: 41M/402M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war) on project cas-pac4j-oauth-server-demo: Error assemblin
g WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cas-pac4j-oauth-server-demo

**Comment by leleuj** [comment]
Yes, the CAS server and management webapps are now Spring boot apps and I need to update the demos in overlays definition. I'll do that when I'll find some time. Feel free to give it a try...

**Comment by bakersemail** [comment]
Switch or clone 4.2.x branch and it should build.
git clone -b 4.2.x https://github.com/leleuj/cas-pac4j-oauth-demo.git

**Comment by leleuj** [comment]
It should be ok on master also.
