### ISSUE TITLE
not redirect to service cas application

### ISSUE THREAD

**Issue by epa64** [leleuj/cas-pac4j-oauth-demo#33]
Hi Jêrome,

I'm 3 servers : 
-CAS (Client Cas)
-CAS2 (Delegate)
-My CAS Application
I'm Using cas-pac4j-oauth-demo 4.2.x branche , when I choice "Cas link" and login on cas2 (jleleu:jleleu), then login success, but it still in cas2 login success page and not redirect to my service.

Best regards
Eric

**Comment by leleuj** [comment]
See my reply on the CAS mailing list...
